const domains = [
    {
      name: ".COM",
      pricePerMonth: 5.99,
      for1Year: 10.99,
    },
    {
      name: ".AI",
      pricePerMonth: 55.99,
      for1Year: 10.99,
    },
    {
      name: ".NET",
      pricePerMonth: 7.99,
      for1Year: 10.99,
    },
    {
      name: ".HEALTH",
      pricePerMonth: 7.99,
      for1Year: 10.99,
    },
    {
      name: ".CO.UK",
      pricePerMonth: 3.99,
      for1Year: 10.99,
    },
    {
      name: ".ORG",
      pricePerMonth: 15.99,
      for1Year: 10.99,
    },
    {
      name: ".CO",
      pricePerMonth: 26.33,
      for1Year: 10.99,
    },
    {
      name: ".SEA",
      pricePerMonth: 26.33,
      for1Year: 10.99,
    }
  ]
    
  const webHostingPlans = [
    {
      name: "Basic Plan",
      pricePerMonth: 4.99,
      storage: "10GB",
      bandwidth: "100GB",
      domains: 1,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Standard Plan",
      pricePerMonth: 9.99,
      storage: "50GB",
      bandwidth: "500GB",
      domains: 5,
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Advanced Plan",
      pricePerMonth: 19.99,
      storage: "100GB",
      bandwidth: "1TB",
      domains: 10,
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Enterprise Plan",
      pricePerMonth: 49.99,
      storage: "Unlimited",
      bandwidth: "Unlimited",
      domains: 25,
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Developer Plan",
      pricePerMonth: 29.99,
      storage: "250GB",
      bandwidth: "2TB",
      domains: 15,
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Pro Plan",
      pricePerMonth: 39.99,
      storage: "500GB",
      bandwidth: "5TB",
      domains: 20,
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Reseller Plan",
      pricePerMonth: 99.99,
      storage: "1TB",
      bandwidth: "10TB",
      domains: 50,
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Custom Plan",
      pricePerMonth: 41.34,
      storage: "100GB",
      bandwidth: "3TB",
      domains: 3,
      SSLCertificate: false,
      for1Year: 10.99,
    },
  ];
  
  
  
  
  const dedicatedServerPlans = [
    {
      name: "Entry-Level Server",
      pricePerMonth: 79.99,
      CPU: "Intel Xeon E3-1230v6",
      RAM: "8GB DDR4",
      storage: "240GB SSD",
      bandwidth: "10TB",
      for1Year: 10.99,
    },
    {
      name: "Mid-Range Server",
      pricePerMonth: 129.99,
      CPU: "Intel Xeon E-2276G",
      RAM: "16GB DDR4",
      storage: "480GB SSD",
      bandwidth: "20TB",
      for1Year: 10.99,
    },
    {
      name: "High-Performance Server",
      pricePerMonth: 199.99,
      CPU: "Intel Xeon Gold 6240",
      RAM: "32GB DDR4",
      storage: "1TB NVMe SSD",
      bandwidth: "30TB",
      for1Year: 10.99,
    },
    {
      name: "storage Server",
      pricePerMonth: 149.99,
      CPU: "Intel Xeon E-2134",
      RAM: "16GB DDR4",
      storage: "4x 4TB HDD",
      bandwidth: "20TB",
      for1Year: 10.99,
    },
    {
      name: "GPU Server",
      pricePerMonth: 299.99,
      CPU: "Intel Xeon E-2236",
      RAM: "64GB DDR4",
      GPU: "NVIDIA GeForce RTX 3080",
      storage: "1TB NVMe SSD",
      bandwidth: "40TB",
      for1Year: 10.99,
    },
    {
      name: "Extrem Server",
      pricePerMonth: 314.55,
      CPU: "Intel Xeon E-4125",
      RAM: "32GB DDR5",
      storage: "6x 4TB HDD",
      bandwidth: "40TB",
      for1Year: 10.99,
    },
    {
      name: "ABC Server",
      pricePerMonth: 512.73,
      CPU: "Intel Xeon E-7152",
      GPU: "NVIDIA GeForce RTX 3090",
      RAM: "64GB DDR5",
      storage: "10x 5TB HDD",
      bandwidth: "50TB",
      for1Year: 10.99,
    },
    {
      name: "EU/Germany Server",
      pricePerMonth: 141.88,
      CPU: "Intel Xeon E-2134",
      RAM: "32GB DDR5",
      storage: "4x 6TB HDD",
      bandwidth: "20TB",
      for1Year: 10.99,
    },
  ];
  
  
  
  const virtualCloudServerPlans = [
    {
      name: "Cloud Server 1",
      vCPUs: 1,
      RAM: "2GB",
      storage: "50GB SSD",
      bandwidth: "1TB",
      pricePerMonth: 5.99,
      for1Year: 10.99,
    },
    {
      name: "Cloud Server 2",
      vCPUs: 2,
      RAM: "4GB",
      storage: "100GB SSD",
      bandwidth: "2TB",
      pricePerMonth: 12.99,
      for1Year: 10.99,
    },
    {
      name: "Cloud Server 4",
      vCPUs: 4,
      RAM: "8GB",
      storage: "200GB SSD",
      bandwidth: "4TB",
      pricePerMonth: 24.99,
      for1Year: 10.99,
    },
    {
      name: "Cloud Server 8",
      vCPUs: 8,
      RAM: "16GB",
      storage: "400GB SSD",
      bandwidth: "8TB",
      pricePerMonth: 49.99,
      for1Year: 10.99,
    },
    {
      name: "Cloud Server 16",
      vCPUs: 16,
      RAM: "32GB",
      storage: "800GB SSD",
      bandwidth: "16TB",
      pricePerMonth: 99.99,
      for1Year: 10.99,
    },
    {
      name: "Cloud Server 32",
      vCPUs: 32,
      RAM: "64GB",
      storage: "1.6TB SSD",
      bandwidth: "32TB",
      pricePerMonth: 199.99,
      for1Year: 10.99,
    },
    {
      name: "US Cloud Server 1",
      vCPUs: 64,
      RAM: "128GB",
      storage: "4TB SSD",
      bandwidth: "64TB",
      pricePerMonth: 259.99,
      for1Year: 10.99,
    },
    {
      name: "US Cloud Server 2",
      vCPUs: 128,
      RAM: "128GB",
      storage: "16TB SSD",
      bandwidth: "128TB",
      pricePerMonth: 400.99,
      for1Year: 10.99,
    },
  ];
  
  
  
  
  
  
  const wordpressHostingPlans = [
    {
      name: "Starter Plan",
      pricePerMonth: 4.99,
      websiteLimit: 1,
      storage: "10GB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Basic Plan",
      pricePerMonth: 7.99,
      websiteLimit: 2,
      storage: "20GB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Standard Plan",
      pricePerMonth: 12.99,
      websiteLimit: 5,
      storage: "50GB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Business Plan",
      pricePerMonth: 24.99,
      websiteLimit: 10,
      storage: "100GB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Pro Plan",
      pricePerMonth: 39.99,
      websiteLimit: 20,
      storage: "200GB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "E-commerce Plan",
      pricePerMonth: 59.99,
      websiteLimit: 50,
      storage: "500GB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Managed Plan",
      pricePerMonth: 79.99,
      websiteLimit: 100,
      storage: "1TB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
    {
      name: "Custom Plan",
      pricePerMonth: 199.99,
      websiteLimit: "Unlimited",
      storage: "2TB",
      bandwidth: "Unlimited",
      SSLCertificate: true,
      for1Year: 10.99,
    },
  ];
  
  
  
  
  const emailHostingPlans = [
    {
      name: "Basic Email",
      pricePerMonth: 2.99,
      emailAccounts: 10,
      storagePerAccount: "5GB",
      customDomain: false,
      spamProtection: true,
      for1Year: 10.99,
    },
    {
      name: "Standard Email",
      pricePerMonth: 4.99,
      emailAccounts: 25,
      storagePerAccount: "10GB",
      customDomain: true,
      spamProtection: true,
      for1Year: 10.99,
    },
    {
      name: "Professional Email",
      pricePerMonth: 7.99,
      emailAccounts: 50,
      storagePerAccount: "20GB",
      customDomain: true,
      spamProtection: true,
      for1Year: 10.99,
    },
    {
      name: "Business Email",
      pricePerMonth: 12.99,
      emailAccounts: 100,
      storagePerAccount: "30GB",
      customDomain: false,
      spamProtection: true,
      for1Year: 10.99,
    },
    {
      name: "Enterprise Email",
      pricePerMonth: 19.99,
      emailAccounts: 250,
      storagePerAccount: "50GB",
      customDomain: true,
      spamProtection: true,
      for1Year: 10.99,
    },
    {
      name: "Secure Email",
      pricePerMonth: 9.99,
      emailAccounts: 25,
      storagePerAccount: "15GB",
      customDomain: true,
      endendEncryption: true,
      for1Year: 10.99,
    },
    {
      name: "Anonymous Email",
      pricePerMonth: 25.99,
      emailAccounts: 1,
      storagePerAccount: "12GB",
      customDomain: false,
      spamProtection: false,
      for1Year: 10.99,
    },
    {
      name: "Premium Email",
      pricePerMonth: 19.99,
      emailAccounts: 100,
      storagePerAccount: "64Gb",
      customDomain: true,
      spamProtection: true,
      for1Year: 10.99,
    },
  ];
  
  
  
  
  const vpsHostingPlans = [
    {
      name: "VPS Plan 1",
      pricePerMonth: 19.99,
      vCPUs: 1,
      RAM: "2GB",
      storage: "40GB SSD",
      bandwidth: "2TB",
      for1Year: 10.99,
    },
    {
      name: "VPS Plan 2",
      pricePerMonth: 29.99,
      vCPUs: 2,
      RAM: "4GB",
      storage: "80GB SSD",
      bandwidth: "4TB",
      for1Year: 10.99,
    },
    {
      name: "VPS Plan 4",
      pricePerMonth: 49.99,
      vCPUs: 4,
      RAM: "8GB",
      storage: "160GB SSD",
      bandwidth: "6TB",
      for1Year: 10.99,
    },
    {
      name: "VPS Plan 8",
      pricePerMonth: 79.99,
      vCPUs: 8,
      RAM: "16GB",
      storage: "320GB SSD",
      bandwidth: "8TB",
      for1Year: 10.99,
    },
    {
      name: "VPS Plan 16",
      pricePerMonth: 129.99,
      vCPUs: 16,
      RAM: "32GB",
      storage: "640GB SSD",
      bandwidth: "10TB",
      for1Year: 10.99,
    },
    {
      name: "VPS Plan 32",
      pricePerMonth: 199.99,
      vCPUs: 32,
      RAM: "64GB",
      storage: "1280GB SSD",
      bandwidth: "20TB",
      for1Year: 10.99,
    },
    {
      name: "Black VPS 1",
      pricePerMonth: 299.99,
      vCPUs: 64,
      RAM: "128GB",
      storage: "4TB SSD",
      bandwidth: "100TB",
      for1Year: 10.99,
    },
    {
      name: "Custom VPS 2",
      pricePerMonth: 98.99,
      vCPUs: 32,
      RAM: "64GB",
      storage: "2TB HDD",
      bandwidth: "28TB",
      for1Year: 10.99,
    },
  ];
  
  
  
  const freeVPSHostingPlans = [
    {
      name: "Free Plan 1",
      vCPUs: 1,
      RAM: "512MB",
      storage: "10GB",
      bandwidth: "1TB",
      monthlyVisits: 1000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 2",
      vCPUs: 2,
      RAM: "1GB",
      storage: "20GB",
      bandwidth: "2TB",
      monthlyVisits: 5000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 3",
      vCPUs: 1,
      RAM: "1GB",
      storage: "30GB",
      bandwidth: "3TB",
      monthlyVisits: 10000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 4",
      vCPUs: 2,
      RAM: "2GB",
      storage: "40GB",
      bandwidth: "4TB",
      monthlyVisits: 20000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 5",
      vCPUs: 1,
      RAM: "2GB",
      storage: "50GB",
      bandwidth: "5TB",
      monthlyVisits: 30000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 6",
      vCPUs: 2,
      RAM: "4GB",
      storage: "60GB",
      bandwidth: "6TB",
      monthlyVisits: 50000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 7",
      vCPUs: 1,
      RAM: "4GB",
      storage: "70GB",
      bandwidth: "7TB",
      monthlyVisits: 75000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
    {
      name: "Free Plan 8",
      vCPUs: 2,
      RAM: "8GB",
      storage: "80GB",
      bandwidth: "8TB",
      monthlyVisits: 100000,
      SSLCertificate: false,
      for1Year: 10.99,
    },
  ];



export { 
                domains, 
                webHostingPlans, 
                dedicatedServerPlans, 
                virtualCloudServerPlans,
                wordpressHostingPlans,
                emailHostingPlans,
                vpsHostingPlans,
                freeVPSHostingPlans
            }